import { Ban, Search } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api, ApiError } from '../api'
import { formatAmount, formatTime } from '../format'
import type { ProductCancellationsReport } from '../types'

export function ProductCancellationsScreen({branchCode,date,shiftId,onUnauthorized}:{branchCode:string;date:string;shiftId:number|null;onUnauthorized:()=>void}) {
  const [user,setUser]=useState(''); const [product,setProduct]=useState(''); const [filters,setFilters]=useState({user:'',product:''}); const [page,setPage]=useState(1); const [data,setData]=useState<ProductCancellationsReport|null>(null); const [error,setError]=useState<string|null>(null)
  useEffect(()=>{const c=new AbortController();setError(null);api.productCancellations(branchCode,date,date,shiftId,filters.user,filters.product,page,c.signal).then(setData).catch((e:unknown)=>{if(e instanceof ApiError&&e.status===401)onUnauthorized();else if(!(e instanceof DOMException))setError(e instanceof Error?e.message:'No fue posible cargar las cancelaciones.')});return()=>c.abort()},[branchCode,date,shiftId,filters,page,onUnauthorized])
  return <div className="screen-stack"><section className="screen-title"><p className="utility-label">Auditoría de productos</p><h1>Productos cancelados</h1><p>Eventos de turnos cerrados y cuentas abiertas. Una cuenta eliminada antes de cobrar permanece visible aunque nunca haya generado cheque.</p></section>
    <section className="operation-grid full"><div className="operation-stat danger-soft"><Ban size={20}/><span>Importe cancelado</span><strong>{formatAmount(data?.totalAmount ?? null)}</strong></div><div className="operation-stat gold-soft"><Ban size={20}/><span>Unidades canceladas</span><strong>{data?.totalQuantity ?? '—'}</strong></div></section>
    <form className="search-form compact-search" onSubmit={e=>{e.preventDefault();setPage(1);setFilters({user:user.trim(),product:product.trim()})}}><Search size={18}/><input value={product} onChange={e=>setProduct(e.target.value)} placeholder="Producto o ID"/><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Empleado"/><button className="secondary-button">Filtrar</button></form>{error?<p className="form-error">{error}</p>:null}
    <section className="content-card"><div className="section-heading"><div><p className="utility-label">Patrones</p><h2>Por empleado y producto</h2></div></div><div className="top-products-grid"><MetricList title="Empleados" data={data?.byEmployee??[]}/><MetricList title="Productos" data={data?.topProducts??[]}/></div></section>
    <section className="content-card"><div className="section-heading"><div><p className="utility-label">Rastro individual</p><h2>Eventos cancelados</h2></div></div>{data?.items.length===0?<p className="quiet-empty">No hay productos cancelados con esos filtros.</p>:<div className="activity-list">{data?.items.map(x=><article className="activity-row cancellation" key={x.eventKey}><span className="activity-icon cancel"><Ban size={18}/></span><div><strong>{x.description||x.productId||'Producto sin descripción'} · {x.quantity??'—'} u.</strong><p>{formatTime(x.cancelledAt)} · {x.user||'Usuario no registrado'} · {x.sourceKind==='TRANSIENT'?'Cuenta abierta':'Histórico'} · {x.accountLabel||`Cuenta ${x.folio??x.tempFolio??'sin folio'}`} · {x.accountStatus}</p><small>{x.reasonDescription||x.reason||'Sin motivo registrado'}{x.shiftId?` · Turno ${x.shiftId}`:''}{x.area?` · ${x.area}`:''}</small></div><b>{formatAmount(x.amount)}</b></article>)}</div>}<div className="pagination-row"><button className="secondary-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button className="secondary-button" disabled={!data?.hasMore} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div></section></div>
}
function MetricList({title,data}:{title:string;data:{label:string;amount:number;quantity:number}[]}){return <div><h3>{title}</h3>{data.length===0?<p className="quiet-empty">Sin datos.</p>:data.map(x=><p key={x.label}><b>{x.label}</b><br/><small>{x.quantity} u. · {formatAmount(x.amount)}</small></p>)}</div>}
